### ISSUE TITLE
为什么不尝试利用GmSSL.java源码

### ISSUE THREAD

**Issue by AndroidMrRen** [pan8664716/GmSSLDemo#1]
public native byte [] publicKeyEncrypt(String algor, byte [] in, byte [] publicKey);
public native byte [] privateKeyDecrypt(String algor, byte [] in, byte [] privateKey);

由于密钥固定死了不好，最好动态生成，我尝试将你的项目修改后和GmSSL Java Wrapper 的GmSSL.c  合并后，将你的native-lib.cpp中的genSM2KeyPairs（）修改成可以返回密钥对的方法，返回16进制的密钥对，然后用上面的非对称算法加密总是不成功，提示：
error:0D07209B:asn1 encoding routines:ASN1_get_object:too long
error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header

-----------------------------------------------
我的代码逻辑：
static {
        System.loadLibrary("gmssl");
 }
gmSSL = new GmSSL()

String[] genSM2KeyPairs = gmSSL.genSM2KeyPairs();

                String sm2PuKey = genSM2KeyPairs[0];//获取SM2 16进制公钥
                String sm2PrKey = genSM2KeyPairs[1];//获取SM2 16进制私钥

                encMsg = gmSSL.publicKeyEncrypt("sm2", ”要加密数据“.getBytes(), sm2PuKey.getBytes());
                System.out.println("公钥:" + sm2PuKey+“\n私钥：“+sm2PrKey );
                System.out.println("密文：" + encMsg);
               decMsg = gmSSL.privateKeyDecrypt("sm2", encMsg, sm2PrKey.getBytes());
                System.out.println("明文：" + decMsg);
------------------------------------------------------

RSA都能成功，没有问题。生成的SM2公钥私钥也没问题。可就是SM2不能加解密。

----------------------------------------------------------------------
JNIEXPORT jbyteArray JNICALL
publicKeyEncrypt(JNIEnv *env, jobject instance, jstring algor, jbyteArray in, jbyteArray key) {
    jbyteArray ret = NULL;
    const char *alg = NULL;
    const unsigned char *inbuf = NULL;
    const unsigned char *keybuf = NULL;
    unsigned char *outbuf = NULL;
    int inlen, keylen;
    size_t outlen;
    int pkey_type;
    const unsigned char *cp;
    EVP_PKEY *pkey = NULL;
    EVP_PKEY_CTX *pkctx = NULL;

    if (!(alg = env->GetStringUTFChars(algor, 0))
        || !(inbuf = (unsigned char *) env->GetByteArrayElements(in, 0))
        || (inlen = env->GetArrayLength(in)) <= 0
        || (inlen = env->GetArrayLength(in)) > 256
        || !(keybuf = (unsigned char *) env->GetByteArrayElements(key, 0))
        || (keylen = env->GetArrayLength(key)) <= 0) {
        goto end;
    }
    cp = keybuf;
    outlen = inlen + 1024;

    if (!strcmp(alg, "sm2")) {
        pkey_type = EVP_PKEY_EC;
    } else if (!strcmp(alg, "ecies")) {
        pkey_type = EVP_PKEY_EC;
    } else if (!strcmp(alg, "rsa")) {
        pkey_type = EVP_PKEY_RSA;
    } else {
        goto end;
    }

    if (!(outbuf = (unsigned char *) OPENSSL_malloc(outlen))
        || !(pkey = d2i_PUBKEY(NULL, &cp, (long) keylen))
        || EVP_PKEY_id(pkey) != pkey_type
        || !(pkctx = EVP_PKEY_CTX_new(pkey, NULL))
        || !EVP_PKEY_encrypt_init(pkctx)
        || !EVP_PKEY_encrypt(pkctx, outbuf, &outlen, inbuf, inlen)) {
        goto end;
    }

    if ((ret = env->NewByteArray(outlen))) {
        env->SetByteArrayRegion(ret, 0, outlen, (jbyte *) outbuf);
    }

    end:
    env->ReleaseStringUTFChars(algor, alg);
    env->ReleaseByteArrayElements(in, (jbyte *) inbuf, JNI_ABORT);
    env->ReleaseByteArrayElements(key, (jbyte *) keybuf, JNI_ABORT);
    OPENSSL_free(outbuf);
    EVP_PKEY_free(pkey);
    EVP_PKEY_CTX_free(pkctx);
    return ret;

}
--------------------------------------------------------------------------------

我想要的结果类似这样

String sm2PuKey= "SM2 16进制公钥";
String sm2PrKey= "SM2 16进制私钥";

 encMsg = gmSSL.publicKeyEncrypt("sm2", plain.getBytes(), sm2PuKey.getBytes());
 decMsg = gmSSL.privateKeyDecrypt("sm2", encMsg, sm2PrKey.getBytes());

那Gmssl.c中的publicKeyEncrypt(JNIEnv *env, jobject instance, jstring algor, jbyteArray in, jbyteArray key) 
该怎么修改，影响RSA同时又支持SM2

**Comment by pan8664716** [comment]
你既然用的是 d2i_PUBKEY 来恢复公钥,那RSA 肯定是用的 i2d_PUBKEY 来转换的公钥,但是SM2我不知道你用的哪种方式,你可以读读代码,推荐你用下面两个进行转换,在试试.
i2o_ECPublicKey()
i2d_ECPrivateKey()

**Comment by AndroidMrRen** [comment]
非常感谢 已经合并

**Comment by duyangs** [comment]
@AndroidMrRen 你后续是如何解决的此问题，求教
